runtime: java
env: flex

liveness_check:
  check_interval_sec: 300
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2

readiness_check:
  check_interval_sec: 60
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 300

resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 10

manual_scaling:
  instances: 1