runtime: java11
instance_class: F2

automatic_scaling:
  max_instances: 1
  min_instances: 0

liveness_check:
  check_interval_sec: 300
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2

readiness_check:
  check_interval_sec: 60
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 300
